name: 'Auto Generate Next Release Tag'
description: 'Automatically generate next release tag incrementally with year, month and iteration based on previous release tag.'
author: 'moxley'
branding:
  color: 'red'
  icon: 'tag'

inputs:
  github_token:
    description: 'Github secrets token'
    required: true

runs:
  using: 'node20'
  main: 'dist/index.js'
