name: Test
on:
  pull_request:
    types: [opened, reopened]
    branches-ignore:
      - "dependabot-updates"
  push:
    branches-ignore:
      - "main"
      - "dependabot/**"

jobs:
  Test:
    name: OS ${{ matrix.os }} + node ${{ matrix.node }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: [20]
        os: [ubuntu-latest]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Sanity testing of the action
        id: generate_release_tag
        uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Manually check release tag
        run: echo "${{ steps.generate_release_tag.outputs.next_release_tag }}"
